--Q1. What is the total revenue generated by male vs female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender

--Q2. Which customers used a discount but still spent more thant the avg amount spent?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (SELECT AVG(purchase_amount) from customer)

--Q3. Which are the top 5 products with the highest avg review rating?
select item_purchased, round(AVG(review_rating::numeric),2) as "Avg product rating"
from customer 
group by item_purchased
order by AVG(review_rating) desc
limit 5

--Q4. Compare the avg purchase amounts between standard and express shipping?
select shipping_type, round(AVG(purchase_amount)) 
from customer
where shipping_type in ('Express', 'Standard')
group by shipping_type


--Q5. Do subscribed customers spend more? Compare avg spend and 
--total revenue between subscriber's and non-subscriber's
select subscription_status, count(customer_id) as total_customers, round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc


--Q6. Which 5 products have the highest percentage of purchases with discount applied?
select item_purchased, round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer 
group by item_purchased
order by discount_rate desc
limit 5

--Q7.Segment customers into new, returning, and loyal based on their total 
--number of previous purchases, and show the count of each segment?
with customer_type as (
select customer_id, previous_purchases, 
CASE 
	when previous_purchases = 1 then 'New'
	when previous_purchases BETWEEN 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer
)
select customer_segment, count(*) as "number of customers"
from customer_type
group by customer_segment


--Q8.what are the top 3 most purchased products within each category?
select * from customer


--Q9.Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
--Q10.what is the revenue contribution of each age group?


